# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_show_picture.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import  QtWidgets
from PyQt5.QtCore import QRect,Qt,QMetaObject,QCoreApplication

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 583)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QRect(120, 30, 541, 261))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.screen_text = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.screen_text.sizePolicy().hasHeightForWidth())
        self.screen_text.setSizePolicy(sizePolicy)
        self.screen_text.setStyleSheet("background-color: rgb(170, 255, 191);")
        self.screen_text.setText("")
        self.screen_text.setObjectName("screen_text")
        self.horizontalLayout.addWidget(self.screen_text)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.screen_picture = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.screen_picture.sizePolicy().hasHeightForWidth())
        self.screen_picture.setSizePolicy(sizePolicy)
        self.screen_picture.setText("")
        self.screen_picture.setObjectName("screen_picture")
        self.horizontalLayout.addWidget(self.screen_picture)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QRect(242, 341, 318, 121))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_show_data = QtWidgets.QPushButton(self.widget1)
        self.pushButton_show_data.setObjectName("pushButton_show_data")
        self.horizontalLayout_2.addWidget(self.pushButton_show_data)
        self.pushButton_show_picture = QtWidgets.QPushButton(self.widget1)
        self.pushButton_show_picture.setObjectName("pushButton_show_picture")
        self.horizontalLayout_2.addWidget(self.pushButton_show_picture)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.Slider_numbers = QtWidgets.QSlider(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_numbers.sizePolicy().hasHeightForWidth())
        self.Slider_numbers.setSizePolicy(sizePolicy)
        self.Slider_numbers.setOrientation(Qt.Horizontal)
        self.Slider_numbers.setObjectName("Slider_numbers")
        self.gridLayout.addWidget(self.Slider_numbers, 0, 1, 1, 1)
        self.lineEdit_numbers = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_numbers.sizePolicy().hasHeightForWidth())
        self.lineEdit_numbers.setSizePolicy(sizePolicy)
        self.lineEdit_numbers.setObjectName("lineEdit_numbers")
        self.gridLayout.addWidget(self.lineEdit_numbers, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.Slider_mean = QtWidgets.QSlider(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_mean.sizePolicy().hasHeightForWidth())
        self.Slider_mean.setSizePolicy(sizePolicy)
        self.Slider_mean.setOrientation(Qt.Horizontal)
        self.Slider_mean.setObjectName("Slider_mean")
        self.gridLayout.addWidget(self.Slider_mean, 1, 1, 1, 1)
        self.lineEdit_mean = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_mean.sizePolicy().hasHeightForWidth())
        self.lineEdit_mean.setSizePolicy(sizePolicy)
        self.lineEdit_mean.setObjectName("lineEdit_mean")
        self.gridLayout.addWidget(self.lineEdit_mean, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget1)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.Slider_var = QtWidgets.QSlider(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_var.sizePolicy().hasHeightForWidth())
        self.Slider_var.setSizePolicy(sizePolicy)
        self.Slider_var.setOrientation(Qt.Horizontal)
        self.Slider_var.setObjectName("Slider_var")
        self.gridLayout.addWidget(self.Slider_var, 2, 1, 1, 1)
        self.lineEdit_var = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_var.sizePolicy().hasHeightForWidth())
        self.lineEdit_var.setSizePolicy(sizePolicy)
        self.lineEdit_var.setObjectName("lineEdit_var")
        self.gridLayout.addWidget(self.lineEdit_var, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_show_data.clicked.connect(MainWindow.show_data)
        self.pushButton_show_picture.clicked.connect(MainWindow.show_picture)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_show_data.setText(_translate("MainWindow", "显示数据"))
        self.pushButton_show_picture.setText(_translate("MainWindow", "显示图像"))
        self.label_3.setText(_translate("MainWindow", "样本数"))
        self.label_4.setText(_translate("MainWindow", "均值"))
        self.label_5.setText(_translate("MainWindow", "方差"))

