# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_stock.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(458, 403)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(54, 10, 373, 231))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("font: 22pt \"Agency FB\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_4 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 50))
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 50))
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_stockname = QtWidgets.QLabel(self.widget)
        self.label_stockname.setObjectName("label_stockname")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_stockname)
        self.label_stockcode = QtWidgets.QLabel(self.widget)
        self.label_stockcode.setObjectName("label_stockcode")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_stockcode)
        self.label_stockclose = QtWidgets.QLabel(self.widget)
        self.label_stockclose.setObjectName("label_stockclose")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_stockclose)
        self.verticalLayout.addLayout(self.formLayout)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(70, 280, 342, 104))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_up = QtWidgets.QPushButton(self.widget1)
        self.pushButton_up.setObjectName("pushButton_up")
        self.horizontalLayout.addWidget(self.pushButton_up)
        self.pushButton_down = QtWidgets.QPushButton(self.widget1)
        self.pushButton_down.setObjectName("pushButton_down")
        self.horizontalLayout.addWidget(self.pushButton_down)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_lookup = QtWidgets.QPushButton(self.widget1)
        self.pushButton_lookup.setObjectName("pushButton_lookup")
        self.gridLayout.addWidget(self.pushButton_lookup, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit_stockcode = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_stockcode.setObjectName("lineEdit_stockcode")
        self.gridLayout.addWidget(self.lineEdit_stockcode, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        self.pushButton_up.clicked.connect(Form.move_up)
        self.pushButton_down.clicked.connect(Form.move_down)
        self.pushButton_lookup.clicked.connect(Form.look_up_stock)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "       股票最新收盘价"))
        self.label.setText(_translate("Form", "股票名称"))
        self.label_4.setText(_translate("Form", "股票代码"))
        self.label_5.setText(_translate("Form", "收盘价"))
        self.label_stockname.setText(_translate("Form", "               "))
        self.label_stockcode.setText(_translate("Form", "               "))
        self.label_stockclose.setText(_translate("Form", "               "))
        self.pushButton_up.setText(_translate("Form", "向上查询"))
        self.pushButton_down.setText(_translate("Form", "向下查询"))
        self.pushButton_lookup.setText(_translate("Form", "查询"))
        self.label_3.setText(_translate("Form", "股票代码"))

