# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_22_Slot.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1105, 824)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(160, 20, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 471, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 491, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 481, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 461, 16))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(150, 200, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 240, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(150, 280, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(150, 320, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setEnabled(True)
        self.checkBox.setGeometry(QtCore.QRect(80, 430, 91, 19))
        self.checkBox.setChecked(True)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(80, 390, 211, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(200, 430, 901, 16))
        self.label_7.setObjectName("label_7")
        self.checkBox_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_2.setGeometry(QtCore.QRect(80, 510, 111, 19))
        self.checkBox_2.setObjectName("checkBox_2")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(80, 460, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 540, 113, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(200, 540, 891, 16))
        self.label_8.setObjectName("label_8")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.close)
        self.pushButton_2.clicked.connect(Form.showFullScreen)
        self.pushButton_3.clicked.connect(Form.showNormal)
        self.pushButton_4.pressed.connect(Form.lower)
        self.checkBox.toggled['bool'].connect(self.lineEdit.setVisible)
        self.checkBox_2.toggled['bool'].connect(self.lineEdit_2.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "信号与槽机制"))
        self.label_2.setText(_translate("Form", "信号：由控件或对象发射出去的消息，比如按钮单击事件就是一个信号"))
        self.label_3.setText(_translate("Form", "槽：用于拦截信号的代码，并执行为函数。槽就是执行信号的函数或方法"))
        self.label_4.setText(_translate("Form", "信号相当于自变量，槽相当于因变量。但是一个信号可以绑定多个槽，"))
        self.label_5.setText(_translate("Form", "一个槽也可以拦截多个信号"))
        self.pushButton.setText(_translate("Form", "关闭窗口"))
        self.pushButton_2.setText(_translate("Form", "屏幕最大化"))
        self.pushButton_3.setText(_translate("Form", "屏幕正常"))
        self.pushButton_4.setText(_translate("Form", "下降一层"))
        self.checkBox.setText(_translate("Form", "显示/隐藏"))
        self.label_6.setText(_translate("Form", "控制文本输入框的显示和隐藏"))
        self.label_7.setText(_translate("Form", "默认为选中状态；通过Toggled(Bool)决定是否勾选，通过setVisible()设置输入框是否显示可见"))
        self.checkBox_2.setText(_translate("Form", "可用/不可用"))
        self.label_8.setText(_translate("Form", "取消勾选enable将默认不可用;；通过Toggled(Bool)决定是否勾选，通过setEnable()设置输入框是否显示可用"))

